---
title: "Week 6 - Tasks"
author: "Viki - Misi"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  prettydoc::html_pretty:
    highlight: github
    theme: cayman
    toc: yes

---

```{r setup, include=FALSE}
library(kableExtra)
library(nycflights13)
library(dplyr)
library(ggplot2)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.pos = 'H') 

```


### How many seats has the airplane which flow the most times from `JFK` to `MCO`?

```{r, dplyr-5, echo=FALSE}
t <-
flights %>% 
  filter(origin=='JFK', dest=='MCO') %>% 
  group_by(tailnum) %>% 
  summarise('flight_times'=n()) %>%
  arrange(-flight_times) %>% 
  head(1)

merge(t,planes ) %>% 
    select(tailnum,seats , flight_times)


```

## The best carriers based on arriving (on average the arr_delay is the least), colors= limegreen and cyan4
```{r, echo=FALSE, message=F, warning=FALSE}
# number of flights from origin
flights %>%
  group_by(carrier)%>%
  summarise('mean_arr_delay'=mean(arr_delay, na.rm = T)) %>%
  arrange(mean_arr_delay) %>% 
  ggplot(aes(x = reorder(carrier, mean_arr_delay), y = mean_arr_delay)) + 
    geom_col(color='limegreen', fill='cyan4')+
    labs( y='Average delay', x = 'Carrier')+theme_linedraw()
  


```



## Average arrival delay by destinations **name** in August

```{r, echo=FALSE, message=F, warning=FALSE}

flights %>%
  filter(month==8) %>% 
  group_by(dest)%>%
  summarise('mean_delay'=mean(arr_delay)) %>%
  arrange(mean_delay) %>% 
  head(10) %>%
  merge(y = airports %>% select('faa', 'name'), by.x = 'dest', by.y = 'faa' ) %>% 
  arrange(mean_delay) %>% 
  ggplot(aes(x = reorder(name, mean_delay), y = mean_delay)) + geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 25, vjust = 0.8, hjust=1))+
  labs( y='Average delay', x = 'Destination', title='Average arrival delay', subtitle = 'by destination')



```


## The most popular airiles **name** from `JFK`
```{r, echo=FALSE}

flights %>%
  filter(origin=='JFK') %>% 
  group_by(carrier) %>%
  summarise('n_flights'=n()) %>%
  arrange(-n_flights) %>% 
  head(10) %>% 
  merge(y = airlines) %>% 
  ggplot(aes(x = reorder(name, n_flights), y = n_flights)) + geom_col()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 25, vjust = 0.8, hjust=1))+
  labs( y='Number of flights', x = 'Destination')+
  coord_flip()




```

